### PR TITLE
Added instead of multiple else if's to fix the logic.

### PR DESCRIPTION
**Pull request by DakshMiglani**
Hi, I've removed else if and added just one else without a new if condition.

### CODE REVIEW

**Comment by DakshMiglani** [comment]
@pepzwee please review and merge.

**Comment by pepzwee** [comment]
If there's no error, but API returns 429 for example it's going to go straight to the else block.

**Comment by DakshMiglani** [comment]
@pepzwee fixed that up

**Comment by DakshMiglani** [comment]
Alright. Fixed.

**Pull request merged**
