### PR TITLE
Add float values for new items

### PR DESCRIPTION
**Pull request by reynirf**
Items received from trade will be given a float value.

### CODE REVIEW

**Comment by JayJay1989** [comment]
@pepzwee , @reynirf After this commit, i get this error:

`2018-01-18T20:18:28.291877+00:00 app[web.1]: /app/index.js:71
2018-01-18T20:18:28.291880+00:00 app[web.1]:         BotM.manager.on('sentOfferChanged', (offer, oldState) => {
2018-01-18T20:18:28.291882+00:00 app[web.1]:              ^
2018-01-18T20:18:28.291883+00:00 app[web.1]: 
2018-01-18T20:18:28.291884+00:00 app[web.1]: TypeError: Cannot read property 'manager' of undefined
2018-01-18T20:18:28.291885+00:00 app[web.1]:     at Object.<anonymous> (/app/index.js:71:14)
2018-01-18T20:18:28.291886+00:00 app[web.1]:     at Module._compile (module.js:635:30)
2018-01-18T20:18:28.291887+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:646:10)
2018-01-18T20:18:28.291888+00:00 app[web.1]:     at Module.load (module.js:554:32)
2018-01-18T20:18:28.291889+00:00 app[web.1]:     at tryModuleLoad (module.js:497:12)
2018-01-18T20:18:28.291890+00:00 app[web.1]:     at Function.Module._load (module.js:489:3)
2018-01-18T20:18:28.291891+00:00 app[web.1]:     at Function.Module.runMain (module.js:676:10)
2018-01-18T20:18:28.291892+00:00 app[web.1]:     at startup (bootstrap_node.js:187:16)
2018-01-18T20:18:28.291893+00:00 app[web.1]:     at bootstrap_node.js:608:3
2018-01-18T20:18:28.411593+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2018-01-18T20:18:28.411921+00:00 app[web.1]: npm ERR! errno 1`

**Comment by pepzwee** [comment]
@JayJay1989 try using the code before this commit and let me know if it works then. If it does I'll take a closer look at this merge.

**Comment by JayJay1989** [comment]
I commented line 67 until 81 and it works

**Comment by pepzwee** [comment]
Thank You. I'll take a look tomorrow once I have time.

**Comment by reynirf** [comment]
This works for me, but I've heavily modified the code. Should've tested this with the original code. This issue is that the output from the getBot request is undefined.

**Pull request merged**
