### PR TITLE
Add float values to items

### PR DESCRIPTION
**Pull request by pepzwee**
Adds float values to bot items if the bot account has CS:GO purchased.

### CODE REVIEW

**Comment by FreddyFish** [comment]
It does for some reason not work on my end. :/

**Comment by xChr11s** [comment]
Are the floats are stored anywhere or are they checked at evry reload again ?
Will test it out later (:

**Comment by pepzwee** [comment]
@FreddyFish Do your bot account(s) have CS:GO?
@xChr11s Checked every reload

**Comment by FreddyFish** [comment]
Yeah it does, and its launching the game as well.

**Comment by FreddyFish** [comment]
Also if we take a look at csg0.trade, only one of the items shows float value.

**Comment by FreddyFish** [comment]
Seems like it's giving up on my end.
"Done floats" is coming up almost instantly, even though my bot is having around 900 items.
I will try to look into this after work, if i find time.

This is what i'm getting:
0|home     | [FloatChecker:Progress] Starting to acquire floats for bot "bot_1". This can take a while if you have a lot of items.
0|home     | [FloatChecker:Progress] Done floats for bot "bot_1".

**Pull request merged**
